apiVersion: v1
kind: Service
metadata:
  name: factorial
  namespace: domix
  labels:
    app: factorial
spec:
  type: ClusterIP
  selector:
    app: factorial
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
