---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial
  namespace: domix
  labels:
    app: factorial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~2.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: factorial
  template:
    metadata:
      labels:
        app: factorial
    spec:
      containers:
      - name: factorial
        image: domix/factorial-service:0.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi

